- type: docker-containers
  hide-by-default: true
  containers:
    stremio-web:
      name: Stremio Web
      url: "http://dwax-debian.tail.dylanwax.com:8080"
      icon: si:stremio
      hide: false
    stremio-server:
      name: Stremio Server
      url: "http://dwax-debian.tail.dylanwax.com:11470"
      icon: si:node-dot-js
      hide: false
    mc-vanillaplus:
      name: Vanilla+ MC
      url: "http://dwax-debian.tail.dylanwax.com:25565"
      icon: si:webpack
      hide: false
    n8n:
      name: n8n
      url: "http://dwax-debian.tail.dylanwax.com:5678"
      icon: si:n8n
      hide: false
    stirlingpdf:
      name: Stirling PDF
      url: "http://dwax-debian.tail.dylanwax.com:8585"
      icon: si:libreofficewriter
      hide: false
    kan-web:
      name: kan-web
      url: "http://dwax-debian.tail.dylanwax.com:3000"
      icon: si:trello
      hide: false
    kan-db:
      name: kan-db
      url: "http://dwax-debian.tail.dylanwax.com:3000"
      icon: si:trello
      hide: false

