- type: monitor
  cache: 1m
  title: Services
  sites:
    - title: Stremio 
      url: "https://stremio.dylanwax.com"
      check-url: "http://dwax-debian.tail.dylanwax.com:8080"
      icon: si:stremio
    - title: n8n 
      url: "https://n8n.dylanwax.com"
      check-url: "http://dwax-debian.tail.dylanwax.com:5678"
      icon: si:n8n
    - title: StirlingPDF
      url: "https://stirlingpdf.dylanwax.com"
      check-url: "http://dwax-debian.tail.dylanwax.com:8585"
      icon: si:libreofficewriter
    - title: kan
      url: "https://kan.dylanwax.com"
      check-url: "http://dwax-debian.tail.dylanwax.com:3000"
      icon: si:trello
    - title: Mealie
      url: "https://mealie.dylanwax.com"
      check-url: "http://dwax-debian.tail.dylanwax.com:9925"
      icon: si:mealie
